# Generated by Django 2.2.12 on 2020-10-19 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time1', models.CharField(max_length=25, verbose_name='TIME 1')),
                ('time2', models.CharField(max_length=25, verbose_name='TIME 2')),
                ('qtdGols_time1', models.IntegerField(verbose_name='GOLS DO TIME 1')),
                ('qtdGols_time2', models.IntegerField(verbose_name='GOLS DO TIME 2')),
                ('isValidoParaAposta', models.BooleanField(default=True)),
                ('campeonato', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credito', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtdGols_time1', models.IntegerField()),
                ('qtdGols_time2', models.IntegerField()),
                ('valor_aposta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('apostador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolaoapp.Jogador')),
                ('partida', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bolaoapp.Partida')),
            ],
        ),
    ]
