# Generated by Django 2.2.12 on 2020-04-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoPartida', models.CharField(max_length=6)),
                ('time1', models.CharField(max_length=6)),
                ('time2', models.CharField(max_length=6)),
                ('time1_gols', models.IntegerField()),
                ('time2_gols', models.IntegerField()),
                ('placar', models.CharField(blank=True, max_length=6)),
            ],
        ),
    ]
