# Generated by Django 2.2.12 on 2020-04-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolaoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='isValidoParaAposta',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='partida',
            name='time1',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='partida',
            name='time2',
            field=models.CharField(max_length=25),
        ),
    ]
