# Generated by Django 2.2.12 on 2020-04-10 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolaoapp', '0002_auto_20200409_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partida',
            old_name='time1_gols',
            new_name='qtdGols_time1',
        ),
        migrations.RenameField(
            model_name='partida',
            old_name='time2_gols',
            new_name='qtdGols_time2',
        ),
    ]
