# Generated by Django 2.2.12 on 2020-04-10 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bolaoapp', '0004_partida_campeonato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credito', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placar', models.CharField(blank=True, max_length=6)),
                ('vencedor', models.CharField(blank=True, max_length=6)),
                ('valor_aposta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('apostador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolaoapp.Jogador')),
            ],
        ),
    ]
