# Generated by Django 2.2.12 on 2020-04-12 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolaoapp', '0006_auto_20200411_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aposta',
            old_name='vencedor',
            new_name='resultado',
        ),
    ]
