# Generated by Django 3.1.2 on 2020-10-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolaoapp', '0007_auto_20200411_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aposta',
            name='placar',
        ),
        migrations.RemoveField(
            model_name='aposta',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='codigoPartida',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='placar',
        ),
        migrations.AddField(
            model_name='aposta',
            name='qtdGols_time1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aposta',
            name='qtdGols_time2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partida',
            name='isValidoParaAposta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='partida',
            name='qtdGols_time1',
            field=models.IntegerField(verbose_name=' GOLS DO TIME 1'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='qtdGols_time2',
            field=models.IntegerField(verbose_name=' GOLS DO TIME 2'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='time1',
            field=models.CharField(max_length=25, verbose_name='TIME 1'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='time2',
            field=models.CharField(max_length=25, verbose_name='TIME 2'),
        ),
    ]
